name: Wait for snap changes
description: Wait for a snap to finish changes.
inputs: 
  snap:
    description: The name of the snap to wait for.
    required: true

runs:
  using: "composite"
  steps:
    - name: Wait for snap
      shell: bash
      run: |
        while [ -n "$(snap changes ${{ inputs.snap }} 2>/dev/null | awk '/^[0-9]+/ {if ($2 != "Done") print $2 }')" ]; do
          echo "Waiting for snap changes on ${{ inputs.snap }} to finish"
          sleep 1
        done
        sleep 1
