name: Set up Juju Dashboard k8s charm
description: Set up the Juju Dashboard k8s charm using the supplied versions.
inputs:
  controller-app:
    required: false
    description: The Juju controller application.
    default: controller
  controller-model:
    required: false
    description: The model containing the Juju controller.
    default: controller
  dashboard-ref:
    description: Git reference to build dashboard from. Cannot be used with `dashboard-resource` or `charm-channel`.
    required: false
  dashboard-resource:
    description: Charm resource revision to use when building charm. Cannot be used with `dashboard-ref` or `charm-channel`.
    required: false
  charm-channel:
    description: If set and this is not called from a PR this will run the e2e tests against a published charm. All other options will be ignored.
    required: false

runs:
  using: "composite"
  steps:
    - name: Set build type
      run: |
        if [ -n "${INPUTS_CHARM_CHANNEL}" ]; then
          # Use the provided charm version.
          echo 'build_type=charm-release' >> "$GITHUB_ENV"
        elif [ -n "${INPUTS_DASHBOARD_RESOURCE}" ]; then
          # Use the provided dashboard image when building the charm.
          echo 'build_type=dashboard-resource' >> "$GITHUB_ENV"
        else
          # Build dashboard from source.
          echo 'build_type=source' >> "$GITHUB_ENV"
        fi
      shell: bash
      env:
        INPUTS_CHARM_CHANNEL: ${{ inputs.charm-channel }}
        INPUTS_DASHBOARD_RESOURCE: ${{ inputs.dashboard-resource }}
    - name: Set up Juju Dashboard release
      if: ${{ env.build_type == 'source' }}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        ref: ${{ inputs.dashboard-ref }}
        path: juju-dashboard-release
        persist-credentials: false
    - name: Get the image and build the charm
      id: dashboard-image
      if: ${{ env.build_type != 'charm-release' }}
      shell: bash
      run: |
        "${{ github.workspace }}/charms/k8s-charm/build.sh" \
          "${build_type}" \
          "${INPUTS_DASHBOARD_RESOURCE}" \
          "--platform ubuntu@24.04:amd64" \
          >> "$GITHUB_OUTPUT"
      env:
        INPUTS_DASHBOARD_RESOURCE: ${{ inputs.dashboard-resource }}
    - name: Import dashboard image to microK8s
      if: ${{ env.build_type == 'source' }}
      shell: bash
      run: docker image save "${STEPS_DASHBOARD_IMAGE_OUTPUTS_ID}" | sudo microk8s ctr image import -
      env:
        STEPS_DASHBOARD_IMAGE_OUTPUTS_ID: ${{ steps.dashboard-image.outputs.id }}
    - name: Switch to controller
      run: juju switch "${INPUTS_CONTROLLER_MODEL}"
      shell: bash
      env:
        INPUTS_CONTROLLER_MODEL: ${{ inputs.controller-model }}
    - name: Deploy charm from channel
      if: ${{ env.build_type == 'charm-release' }}
      run: juju deploy juju-dashboard-k8s dashboard --channel "${INPUTS_CHARM_CHANNEL}"
      shell: bash
      env:
        INPUTS_CHARM_CHANNEL: ${{ inputs.charm-channel }}
    - name: Deploy built charm
      if: ${{ env.build_type != 'charm-release' }}
      run: juju deploy ${{ github.workspace }}/charms/k8s-charm/juju-dashboard*.charm dashboard --resource "dashboard-image=${STEPS_DASHBOARD_IMAGE_OUTPUTS_ID}"
      shell: bash
      env:
        STEPS_DASHBOARD_IMAGE_OUTPUTS_ID: ${{ steps.dashboard-image.outputs.id }}
    - name: Integrate charm
      run: juju integrate "${INPUTS_CONTROLLER_APP}" dashboard
      shell: bash
      env:
        INPUTS_CONTROLLER_APP: ${{ inputs.controller-app }}
    - name: Wait for charm to be ready
      uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
      with:
        timeout_minutes: 1
        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
        command: |
          STATUS=$(juju status --format json | yq .applications.dashboard.application-status.current)
          if [ "$STATUS" == "error" ]; then
            # Sometimes the dashboard unit will get into an error state, so resolve and try again.
            juju resolved dashboard/0
          fi
          TYPE=application NAME=dashboard TIMEOUT_MINUTES=1 EXPECTED_STATUS=active ./scripts/wait-for
    - name: Disable analytics
      run: juju config dashboard analytics-enabled=false
      shell: bash
    - name: Clean up
      run: |
        # Delete build files to save space. Pass `|| true` so that an error is not thrown if the directories don't exist.
        rm -rf "${{ github.workspace }}/juju-dashboard-release" || true
      shell: bash
