name: Set up Juju Dashboard k8s charm
description: Set up the Juju Dashboard k8s charm using the supplied versions.
inputs:
  controller-app:
    required: false
    description: The Juju controller application.
    default: controller
  controller-model:
    required: false
    description: The model containing the Juju controller.
    default: controller
  dashboard-ref:
    description: Git reference to build dashboard from. Cannot be used with `dashboard-resource` or `charm-channel`.
    required: false
  dashboard-resource:
    description: Charm resource revision to use when building charm. Cannot be used with `dashboard-ref` or `charm-channel`.
    required: false
  charm-channel:
    description: If set and this is not called from a PR this will run the e2e tests against a published charm. All other options will be ignored.
    required: false
    type: choice
    options:
      - latest/stable
      - latest/beta
      - latest/edge
  dashboard-charm-ref:
    description: Git reference to use when cloning charm repository.
    required: false

runs:
  using: "composite"
  steps:
    - name: Set build type
      run: |
        if [ -n "${{ inputs.charm-channel }}" ]; then
          # Use the provided charm version.
          echo 'build_type=charm-release' >> "$GITHUB_ENV"
        elif [ -n "${{ inputs.dashboard-resource }}" ]; then
          # Use the provided dashboard image when building the charm.
          echo 'build_type=dashboard-resource' >> "$GITHUB_ENV"
        else
          # Build dashboard from source.
          echo 'build_type=checkout' >> "$GITHUB_ENV"
        fi
      shell: bash
    - name: Check out Juju Dashboard charm
      if: ${{ env.build_type == 'checkout' || env.build_type == 'dashboard-resource' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.dashboard-charm-ref }}
        repository: canonical/juju-dashboard-charm
        path: juju-dashboard-charm
    - name: Set up Juju Dashboard release
      if: ${{ env.build_type == 'checkout' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.dashboard-ref }}
        path: juju-dashboard-release
    - name: Build Juju Dashboard image
      if: ${{ env.build_type == 'checkout' }}
      shell: bash
      run: |
        cd '${{ github.workspace }}/juju-dashboard-release'
        DOCKER_BUILDKIT=1 docker build -t juju-dashboard:local .
        docker image save juju-dashboard:local | sudo microk8s ctr image import -
    - name: Choose dashboard image
      id: dashboard-image
      shell: bash
      if: ${{ env.build_type == 'checkout' || env.build_type == 'dashboard-resource' }}
      run: |
        case '${{ env.build_type }}' in
          'checkout')
            ID='juju-dashboard:local'
          ;;
          'dashboard-resource')
            ID='canonicalwebteam/juju-dashboard:${{ inputs.dashboard-resource }}'
          ;;
        esac
        echo "id=$ID" >> "$GITHUB_OUTPUT"
    - name: Install charmcraft
      if: ${{ env.build_type != 'charm-release' }}
      run: sudo snap install charmcraft --classic
      shell: bash
    - name: Wait for charmcraft snap
      if: ${{ env.build_type != 'charm-release' }}
      uses: ./.github/actions/wait-for-snap
      with:
        snap: charmcraft
    - name: Build the charm
      if: ${{ env.build_type != 'charm-release' }}
      run: |
        cd ${{ github.workspace }}/juju-dashboard-charm/k8s-charm
        charmcraft pack
      shell: bash
    - name: Switch to controller
      run: juju switch '${{ inputs.controller-model }}'
      shell: bash
    - name: Deploy charm from channel
      if: ${{ env.build_type == 'charm-release' }}
      run: juju deploy juju-dashboard-k8s dashboard --channel '${{ inputs.charm-channel }}'
      shell: bash
    - name: Deploy built charm
      if: ${{ env.build_type != 'charm-release' }}
      run: juju deploy ${{ github.workspace }}/juju-dashboard-charm/k8s-charm/juju-dashboard*.charm dashboard --resource 'dashboard-image=${{ steps.dashboard-image.outputs.id }}'
      shell: bash
    - name: Integrate charm
      run: juju integrate '${{ inputs.controller-app }}' dashboard
      shell: bash
    - name: Wait for charm to be ready
      run: juju wait-for application dashboard
      shell: bash
    - name: Disable analytics
      run: juju config dashboard analytics-enabled=false
      shell: bash
    - name: Clean up
      run: |
        # Delete build files to save space. Pass `|| true` so that an error is not thrown in the directories don't exist.
        rm -rf '${{ github.workspace }}/juju-dashboard-charm' || true
        rm -rf '${{ github.workspace }}/juju-dashboard-release' || true
      shell: bash
