name: Set up Juju Dashboard machine charm
description: Set up the Juju Dashboard machine charm using the supplied versions.
inputs:
  dashboard-ref:
    description: Git reference to build dashboard from. Cannot be used with `dashboard-resource` or `charm-channel`.
    required: false
  bundled-dashboard:
    description: If `true`, use the version of the dashboard that's bundled in the charm repository. If set, other inputs will be ignored.
    required: false
  dashboard-version:
    description: Use a specific version of the dashboard when building the charm.
    required: false
  charm-channel:
    description: If set and this is not called from a PR this will run the e2e tests against a published charm. All other options will be ignored.
    required: false
  controller-app:
    required: false
    description: The Juju controller application.
    default: controller
  controller-model:
    required: false
    description: The model containing the Juju controller.
    default: controller

runs:
  using: "composite"
  steps:
    - name: Set build type
      run: |
        if [ -n "${INPUTS_CHARM_CHANNEL}" ]; then
          # Use the provided charm version.
          echo 'build_type=charm-release' >> "$GITHUB_ENV"
        elif [ -n "${INPUTS_DASHBOARD_VERSION}" ]; then
          # Use a specific dashboard version.
          echo 'build_type=dashboard-version' >> "$GITHUB_ENV"
        elif [ "${INPUTS_BUNDLED_DASHBOARD}" == "true" ]; then
          # Use the version of the dashboard that's bundled in the repository.
          echo 'build_type=bundled-dashboard' >> "$GITHUB_ENV"
        else
          # Build dashboard from source.
          echo 'build_type=source' >> "$GITHUB_ENV"
        fi
      shell: bash
      env:
        INPUTS_CHARM_CHANNEL: ${{ inputs.charm-channel }}
        INPUTS_DASHBOARD_VERSION: ${{ inputs.dashboard-version }}
        INPUTS_BUNDLED_DASHBOARD: ${{ inputs.bundled-dashboard }}
    - name: Set up Juju Dashboard release
      if: ${{ env.build_type != 'charm-release' }}
      shell: bash
      run: |
        "${{ github.workspace }}/charms/machine-charm/build.sh" \
          "${build_type}" \
          "${INPUTS_DASHBOARD_VERSION}" \
          "--platform ubuntu@24.04:amd64"
      env:
        INPUTS_DASHBOARD_VERSION: ${{ inputs.dashboard-version }}
    - name: Switch to controller
      run: juju switch '${INPUTS_CONTROLLER_MODEL}'
      shell: bash
      env:
        INPUTS_CONTROLLER_MODEL: ${{ inputs.controller-model }}
    - name: Deploy charm from channel
      if: ${{ env.build_type == 'charm-release' }}
      run: juju deploy juju-dashboard dashboard --channel '${INPUTS_CHARM_CHANNEL}'
      shell: bash
      env:
        INPUTS_CHARM_CHANNEL: ${{ inputs.charm-channel }}
    - name: Deploy built charm
      if: ${{ env.build_type != 'charm-release' }}
      run: juju deploy ${{ github.workspace }}/charms/machine-charm/juju-dashboard*.charm dashboard
      shell: bash
    - name: Wait for charm to be ready for integration
      uses: ./.github/actions/juju-wait-for
      with:
        type: application
        name: dashboard
        status: blocked
    - name: Integrate charm
      run: juju integrate '${INPUTS_CONTROLLER_APP}' dashboard
      shell: bash
      env:
        INPUTS_CONTROLLER_APP: ${{ inputs.controller-app }}
    - name: Wait for charm to be ready
      uses: ./.github/actions/juju-wait-for
      with:
        type: application
        name: dashboard
        status: active
    - name: Disable analytics
      run: juju config dashboard analytics-enabled=false
      shell: bash
