name: Cut release PR
description: Cut a release PR

runs:
  using: node20
  main: index.js

inputs:
  github-token:
    description: "GitHub Token (usually `secrets.GITHUB_TOKEN`)."
    required: true

outputs:
  cut-pr-number:
    description: Number of the cut PR.

  cut-branch:
    description: Name of the release branch that has been cut.
