name: Run Playwright
description: Install and run Playwright tests.
inputs:
  test-identifier:
    description: Unique identifier for this test run that will be used for uploading test results.
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
    - name: Install Playwright Browsers
      run: yarn dlx playwright install --with-deps
      shell: bash
    - name: Get dashboard address
      id: dashboard
      run: echo "address=http://$(juju show-unit dashboard/0 | yq '.dashboard/0.public-address'):8080" >> $GITHUB_OUTPUT
      shell: bash
    - name: Run Playwright tests
      run: |
        cd ${{ github.workspace }}
        yarn playwright test
      shell: bash
      env: 
        DASHBOARD_ADDRESS: ${{ steps.dashboard.outputs.address }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: ${{ inputs.test-identifier }}
        path: test-results/
        retention-days: 30
