name: Send Mattermost notification
description: Sends the provided content to a Mattermost channel.
inputs:
  channel:
    description: Mattermost channel to send message to.
    required: false
    default: juju-dashboard
  webhook-url:
    description: Webhook URL to send use.
    required: true
  message:
    description: Custom message to send, instead of default 'workflow failed'.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Send workflow failure notification
      shell: bash
      if: inputs.message == ''
      run: |
        curl -X POST \
            -F 'workflow=${GITHUB_WORKFLOW}' \
            -F 'repo_name=${{ github.repository }}' \
            -F 'action_id=${{ github.run_id }}' \
            '${INPUTS_WEBHOOK_URL}?room=${INPUTS_CHANNEL}'
      env:
        INPUTS_WEBHOOK_URL: ${{ inputs.webhook-url }}
        INPUTS_CHANNEL: ${{ inputs.channel }}
    - name: Send notification with custom message
      shell: bash
      if: inputs.message != ''
      run: |
        # URI encode the mesage using JQ
        message="$(echo -n '${INPUTS_MESSAGE}' | jq -sRr @uri)"

        curl -X POST \
            "${INPUTS_WEBHOOK_URL}?room=${INPUTS_CHANNEL}&custom_message=$message"
      env:
        INPUTS_MESSAGE: ${{ inputs.message }}
        INPUTS_WEBHOOK_URL: ${{ inputs.webhook-url }}
        INPUTS_CHANNEL: ${{ inputs.channel }}
