#!/bin/bash

rm -rf \
  node_modules/ \
  build/ \
  .docker-project \
  .yarn.canonical-webteam-juju-dashboard* \
  yarn-error.log \
  .yarn/cache \
  .yarn/install-state.gz \
  juju-dashboard-*.tar.bz2 \
  coverage \
