name: Juju Wait For
description: Wait for a Juju application, unit or model to reach a specific state.
inputs:
  type:
    description: "The type of resource to wait for"
    required: true
  name:
    description: "The name of the resource to wait for"
    required: true
  model-name:
    description: "The resource's model. The current model will be used if not provided. Not required if the type is set to 'model'"
    required: false
  timeout_minutes:
    description: "Timeout duration in minutes"
    required: false
    default: "5"
  status:
    description: "Expected status for polling. Comma-separated for multiple statuses."
    required: false
    default: "active"

runs:
  using: composite
  steps:
    - name: Wait for Juju resource
      shell: bash
      run: |
        ./scripts/wait-for
      env:
        TYPE: ${{ inputs.type }}
        NAME: ${{ inputs.name }}
        MODEL_NAME: ${{ inputs.model-name }}
        TIMEOUT_MINUTES: ${{ inputs.timeout_minutes }}
        EXPECTED_STATUS: ${{ inputs.status }}
