export enum TestId {
  STATUS_GROUP = "status-group",
  OWNER_GROUP = "owner-group",
  CLOUD_GROUP = "cloud-group",
  COLUMN_NAME = "column-name",
  COLUMN_SUMMARY = "column-summary",
  COLUMN_OWNER = "column-owner",
  COLUMN_CLOUD = "column-cloud",
  COLUMN_CREDENTIAL = "column-credential",
  COLUMN_CONTROLLER = "column-controller",
  COLUMN_UPDATED = "column-updated",
  COLUMN_ACTIONS = "column-actions",
  COLUMN_STATUS = "column-status",
  COLUMN_REGION = "column-region",
}
