name: Test Charms
on:
  push:
    paths:
      - "charms/**"
  pull_request:
    paths:
      - "charms/**"

permissions: read-all

jobs:
  test-charm:
    name: Test ${{ matrix.charm-type }} charm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        charm-type: [machine, k8s]
    defaults:
      run:
        working-directory: "charms/${{ matrix.charm-type }}-charm"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14"
      - name: Install requirements
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements-dev.txt
      - name: Run tests
        run: ./run_tests
